#!/bin/bash

# 智能自动激活函数
uvm_auto_activate() {
    local uvm_envs_dir="${UVM_ENVS_DIR:-${HOME}/uv_envs}"
    
    # 优先级 1: 检查项目本地 .venv（向上查找到根目录）
    local current_dir="$PWD"
    while [ "$current_dir" != "/" ] && [ "$current_dir" != "" ]; do
        if [ -d "$current_dir/.venv" ]; then
            local activate_script=""
            if [ -f "$current_dir/.venv/bin/activate" ]; then
                activate_script="$current_dir/.venv/bin/activate"
            elif [ -f "$current_dir/.venv/Scripts/activate" ]; then
                # Windows Git Bash
                activate_script="$current_dir/.venv/Scripts/activate"
            fi
            
            if [ -n "$activate_script" ]; then
                # 检查是否已经激活了这个环境
                if [ "$VIRTUAL_ENV" != "$current_dir/.venv" ]; then
                    # 如果有其他环境激活，先停用
                    if [ -n "$VIRTUAL_ENV" ] && command -v deactivate &> /dev/null; then
                        deactivate 2>/dev/null || true
                    fi
                    
                    echo "🔄 Auto-activating local .venv"
                    source "$activate_script"
                    export UVM_AUTO_ACTIVATED="local"
                    export UVM_AUTO_ACTIVATED_PATH="$current_dir/.venv"
                fi
                return 0
            fi
        fi
        
        # 向上一级目录
        current_dir=$(dirname "$current_dir")
    done
    
    # 优先级 2: 检查 .uvmrc（共享环境）
    if [ -f ".uvmrc" ]; then
        local env_name=$(cat .uvmrc | tr -d '[:space:]' | head -n 1)
        
        if [ -n "$env_name" ]; then
            local env_path="$uvm_envs_dir/$env_name"
            
            # 检查环境是否存在
            local activate_script=""
            if [ -d "$env_path" ]; then
                if [ -f "$env_path/bin/activate" ]; then
                    activate_script="$env_path/bin/activate"
                elif [ -f "$env_path/Scripts/activate" ]; then
                    activate_script="$env_path/Scripts/activate"
                fi
            fi
            
            if [ -n "$activate_script" ]; then
                # 检查是否已经激活了这个环境
                if [ "$VIRTUAL_ENV" != "$env_path" ]; then
                    # 如果有其他环境激活，先停用
                    if [ -n "$VIRTUAL_ENV" ] && command -v deactivate &> /dev/null; then
                        deactivate 2>/dev/null || true
                    fi
                    
                    echo "🔄 Auto-activating uvm environment: $env_name"
                    source "$activate_script"
                    export UVM_AUTO_ACTIVATED="uvm:$env_name"
                    export UVM_AUTO_ACTIVATED_PATH="$env_path"
                fi
                return 0
            else
                echo "⚠️  Environment '$env_name' specified in .uvmrc not found"
                echo "   Run 'uvm create $env_name' to create it"
            fi
        fi
    fi
    
    # 如果都不满足，且之前有自动激活的环境，则停用
    if [ -n "$UVM_AUTO_ACTIVATED" ] && [ -n "$VIRTUAL_ENV" ]; then
        # 检查是否离开了激活环境的目录
        local should_deactivate=true
        
        # 如果是本地 .venv，检查是否还在项目目录内
        if [ "$UVM_AUTO_ACTIVATED" = "local" ] && [ -n "$UVM_AUTO_ACTIVATED_PATH" ]; then
            local venv_project_dir=$(dirname "$UVM_AUTO_ACTIVATED_PATH")
            # 检查当前路径是否在项目目录下
            case "$PWD" in
                "$venv_project_dir"*)
                    should_deactivate=false
                    ;;
            esac
        fi
        
        # 如果是 .uvmrc 环境，检查当前目录是否还有 .uvmrc
        if [[ "$UVM_AUTO_ACTIVATED" == uvm:* ]] && [ -f ".uvmrc" ]; then
            should_deactivate=false
        fi
        
        if [ "$should_deactivate" = true ]; then
            echo "🔻 Deactivating environment (left project directory)"
            if command -v deactivate &> /dev/null; then
                deactivate 2>/dev/null || true
            fi
            unset UVM_AUTO_ACTIVATED
            unset UVM_AUTO_ACTIVATED_PATH
        fi
    fi
}

# 生成 Shell 钩子代码
uvm_generate_shell_hook() {
    cat <<'EOF'
# UVM Shell Hook - Auto-activation support
# Generated by uvm shell-hook

# Load UVM configuration
export UVM_HOME="${UVM_HOME:-${HOME}/.config/uvm}"
if [ -f "${UVM_HOME}/config" ]; then
    source "${UVM_HOME}/config"
fi

# Set default environment directory
export UVM_ENVS_DIR="${UVM_ENVS_DIR:-${HOME}/uv_envs}"

# Auto-activation function
uvm_auto_activate() {
    local uvm_envs_dir="${UVM_ENVS_DIR:-${HOME}/uv_envs}"
    
    # Priority 1: Check for local .venv
    local current_dir="$PWD"
    while [ "$current_dir" != "/" ] && [ "$current_dir" != "" ]; do
        if [ -d "$current_dir/.venv" ]; then
            local activate_script=""
            if [ -f "$current_dir/.venv/bin/activate" ]; then
                activate_script="$current_dir/.venv/bin/activate"
            elif [ -f "$current_dir/.venv/Scripts/activate" ]; then
                activate_script="$current_dir/.venv/Scripts/activate"
            fi
            
            if [ -n "$activate_script" ]; then
                if [ "$VIRTUAL_ENV" != "$current_dir/.venv" ]; then
                    if [ -n "$VIRTUAL_ENV" ] && command -v deactivate &> /dev/null; then
                        deactivate 2>/dev/null || true
                    fi
                    source "$activate_script"
                    export UVM_AUTO_ACTIVATED="local"
                    export UVM_AUTO_ACTIVATED_PATH="$current_dir/.venv"
                fi
                return 0
            fi
        fi
        current_dir=$(dirname "$current_dir")
    done
    
    # Priority 2: Check for .uvmrc
    if [ -f ".uvmrc" ]; then
        local env_name=$(cat .uvmrc | tr -d '[:space:]' | head -n 1)
        
        if [ -n "$env_name" ]; then
            local env_path="$uvm_envs_dir/$env_name"
            local activate_script=""
            
            if [ -d "$env_path" ]; then
                if [ -f "$env_path/bin/activate" ]; then
                    activate_script="$env_path/bin/activate"
                elif [ -f "$env_path/Scripts/activate" ]; then
                    activate_script="$env_path/Scripts/activate"
                fi
            fi
            
            if [ -n "$activate_script" ]; then
                if [ "$VIRTUAL_ENV" != "$env_path" ]; then
                    if [ -n "$VIRTUAL_ENV" ] && command -v deactivate &> /dev/null; then
                        deactivate 2>/dev/null || true
                    fi
                    source "$activate_script"
                    export UVM_AUTO_ACTIVATED="uvm:$env_name"
                    export UVM_AUTO_ACTIVATED_PATH="$env_path"
                fi
                return 0
            fi
        fi
    fi
    
    # Deactivate if left project directory
    if [ -n "$UVM_AUTO_ACTIVATED" ] && [ -n "$VIRTUAL_ENV" ]; then
        local should_deactivate=true
        
        if [ "$UVM_AUTO_ACTIVATED" = "local" ] && [ -n "$UVM_AUTO_ACTIVATED_PATH" ]; then
            local venv_project_dir=$(dirname "$UVM_AUTO_ACTIVATED_PATH")
            case "$PWD" in
                "$venv_project_dir"*)
                    should_deactivate=false
                    ;;
            esac
        fi
        
        if [[ "$UVM_AUTO_ACTIVATED" == uvm:* ]] && [ -f ".uvmrc" ]; then
            should_deactivate=false
        fi
        
        if [ "$should_deactivate" = true ]; then
            if command -v deactivate &> /dev/null; then
                deactivate 2>/dev/null || true
            fi
            unset UVM_AUTO_ACTIVATED
            unset UVM_AUTO_ACTIVATED_PATH
        fi
    fi
}

# Hook into cd command
_uvm_original_cd=$(declare -f cd | tail -n +2)
cd() {
    builtin cd "$@"
    local ret=$?
    uvm_auto_activate
    return $ret
}

# Also check on shell initialization
uvm_auto_activate

# Helper function to get environment path
_uvm_get_env_path() {
    local env_name="$1"
    local uvm_envs_dir="${UVM_ENVS_DIR:-${HOME}/uv_envs}"
    local uvm_envs_file="${HOME}/.config/uvm/envs.json"
    
    # Try default path first
    local default_path="${uvm_envs_dir}/${env_name}"
    if [ -d "${default_path}" ]; then
        echo "${default_path}"
        return 0
    fi
    
    # Try to find in envs.json
    if [ -f "${uvm_envs_file}" ]; then
        local path=$(grep -o "\"name\":\"${env_name}\"[^}]*\"path\":\"[^\"]*\"" "${uvm_envs_file}" | grep -o "\"path\":\"[^\"]*\"" | cut -d'"' -f4)
        if [ -n "$path" ] && [ -d "$path" ]; then
            echo "$path"
            return 0
        fi
    fi
    
    return 1
}

# Make uvm commands available as shell functions
uvm() {
    if [ "$1" = "activate" ]; then
        # Special handling for activate to work in current shell
        shift
        local env_name="$1"
        
        if [ -z "$env_name" ]; then
            echo "Error: Environment name is required"
            echo "Usage: uvm activate <env_name>"
            return 1
        fi
        
        # Get environment path
        local env_path=$(_uvm_get_env_path "$env_name")
        
        if [ -z "$env_path" ]; then
            echo "Error: Environment '$env_name' not found"
            echo "Run 'uvm list' to see available environments"
            return 1
        fi
        
        local activate_script=""
        if [ -f "$env_path/bin/activate" ]; then
            activate_script="$env_path/bin/activate"
        elif [ -f "$env_path/Scripts/activate" ]; then
            activate_script="$env_path/Scripts/activate"
        fi
        
        if [ -n "$activate_script" ]; then
            source "$activate_script"
            export UVM_ACTIVE_ENV="$env_name"
            echo "✓ Environment '$env_name' activated"
        else
            echo "Error: Activate script not found"
            return 1
        fi
    elif [ "$1" = "deactivate" ]; then
        # Special handling for deactivate
        if [ -n "$VIRTUAL_ENV" ] && command -v deactivate &> /dev/null; then
            deactivate
            unset UVM_ACTIVE_ENV
            unset UVM_AUTO_ACTIVATED
            unset UVM_AUTO_ACTIVATED_PATH
            echo "✓ Environment deactivated"
        else
            echo "No active environment to deactivate"
        fi
    else
        # Call the actual uvm binary for other commands
        command uvm "$@"
    fi
}
EOF
}

